/**
 * Style Dictionary build config.
 *
 * Reads DTCG tokens from `tokens/` and emits CSS custom properties to
 * `public/styles/tokens.css` (gitignored; regenerated by `vp run tokens`).
 * The generated file is copied into `dist/` by Vite's public dir handling
 * and linked into every page by the bare-shell plugin.
 */
export default {
  source: ["tokens/**/*.tokens.json"],
  platforms: {
    css: {
      transformGroup: "css",
      prefix: "rkn",
      buildPath: "public/styles/",
      files: [
        {
          destination: "tokens.css",
          format: "css/variables",
          options: {
            outputReferences: true,
          },
        },
      ],
    },
  },
};
