/**
 * Style Dictionary build config.
 *
 * Reads DTCG tokens from `tokens/` and emits CSS custom properties to
 * `styles/tokens.css` (gitignored; regenerated by `vpr tokens`).
 * `styles/site.css` imports it, so the variables end up in the single
 * stylesheet that Lightning CSS compiles.
 */
export default {
  source: ["tokens/**/*.tokens.json"],
  platforms: {
    css: {
      transformGroup: "css",
      prefix: "rkn",
      buildPath: "styles/",
      files: [
        {
          destination: "tokens.css",
          format: "css/variables",
          options: {
            outputReferences: true,
          },
        },
      ],
    },
  },
};
