/**
 * Commits the VRT baselines regenerated by `vpr vrt:update`.
 *
 * Run by the "Update VRT snapshots" workflow, which dispatches on a branch
 * and pushes the Linux baselines CI compares against.
 */
import { execFileSync } from "node:child_process";

const SNAPSHOTS = "tests/vrt/__screenshots__";

function git(...args: string[]): string {
  return execFileSync("git", args, {
    encoding: "utf-8",
    stdio: ["ignore", "pipe", "inherit"],
  });
}

git("config", "user.name", "github-actions[bot]");
git("config", "user.email", "github-actions[bot]@users.noreply.github.com");
git("add", SNAPSHOTS);

if (git("diff", "--cached", "--name-only").trim() === "") {
  console.log("No snapshot changes.");
} else {
  git("commit", "-m", "test: update VRT snapshots");
  git("push");
}
